



   

   






  
  
    
  
   
     




#include <iostream>

using namespace std;

int main(){ 

int k=0,n,l=0, m=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0;

 char a,b,c,d,e, f,g,i,h,j;

 int kk, ll, mm, nn, oo, pp,qq,rr,ss,tt;

cout<<"à¤†à¤ªà¤•à¥‹ à¤•à¤¿à¤¸à¥€ à¤¨à¥‡ ðŸ’° â‚¹164 à¤¦à¤¿à¤ à¤•à¥à¤¯à¤¾ à¤†à¤ª ðŸ¤”à¤¬à¤¤à¤¾ à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆ à¤•à¥€ ðŸ’¶â‚¹100 à¤•à¥‡ à¤•à¤¿à¤¤à¤¨à¥‡ à¤¨à¥‹à¤Ÿ à¤²à¤—à¥‡à¤‚à¤—à¥‡ à¤”à¤°,ðŸª™ â‚¹5 à¤•à¥‡ à¤•à¤¿à¤¤à¤¨à¥‡ à¤¸à¤¿à¤•à¥à¤•à¥‡ à¤²à¤¾à¤—à¥‡à¤‚à¤— à¤”à¤° â‚¹2 à¤•à¥‡ à¤•à¤¿à¤¤à¤¨à¥‡ à¤²à¤—à¥‡à¤‚à¤—à¥‡ "<<"\n";

cout<<"à¤¯à¤¹à¤¾à¤‚ à¤ªà¤° à¤‡à¤¸ à¤ªà¥à¤°à¤•à¤¾à¤° à¤•à¥‡ questions ko à¤†à¤¸à¤¾à¤¨à¥€ à¤¸à¥‡ðŸ¤· solve à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚, à¤•à¤¿à¤¸à¥€ à¤¨à¥‡  à¤•à¥‹à¤ˆ à¤­à¥€ value (money) à¤ªà¥‚à¤›à¤¾ à¤¹à¥‹ à¤µà¤¹ enter à¤•à¤°à¥‡ ðŸª™â‚¹1 à¤¸à¥‡ðŸ’¶ â‚¹100à¤²à¤¾à¤– à¤¤à¤• ,, à¤”à¤° à¤•à¥à¤› easy questions à¤•à¥‡ answer à¤¦à¥‡à¤¤à¥‡ à¤°à¤¹à¥‡ à¥¤ à¤†à¤ªà¤•à¥‹ answer à¤®à¤¿à¤²à¤¤à¥‡ à¤°à¤¹à¥‡à¤‚à¤—à¥‡ à¥¤" <<"\n"<<"\n";

cin>>n;

if (n==0){

goto final;}

else if (n<2){

goto one;}

else if (n<5&&n>=2){

goto two;}

else if (n<10&&n>=5){

goto five;}

else if (n<20&&n>=10){

goto ten;}

else if (n<50&&n>=20){

goto twenty;}

else if (n<100&&n>=50){

goto fifty;}

else if (n<200&&n>=100){

goto hundred;}

else if (n<500&&n>=200){

goto twohundred;}

if (n<2000&&n>=500){

goto fivehundred;}

//else{

//cout<<"U have entered wrong value "; }

cout<<"â‚¹2000 à¤•à¥‡ à¤¨à¥‹à¤Ÿ à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>a; 

if (a=='h'){

k=n/2000;

cout<<"â‚¹2000 à¤•à¥‡ "<<k <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

kk=(n-(2000*k));

cout<<"à¤¶à¥‡à¤· â‚¹"<<(n-(2000*k))<<"\n"<<"\n"; 

if (kk==0)

goto final;

else if (kk<500)

goto twohundred;

fivehundred:

cout<<"â‚¹500 à¤•à¥‡ à¤¨à¥‹à¤Ÿ  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>b ;

if (b=='h'){

l=(n-2000*k)/500; 

cout<<"â‚¹500 à¤•à¥‡ "<< l <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·   â‚¹"<<(n-(2000*k)-500*l)<<"\n"<<"\n";

ll=(n-(2000*k)-500*l);

if (ll==0)

goto final;

else if (ll<200)

goto hundred;

twohundred:

cout<<"â‚¹200 à¤•à¥‡ à¤¨à¥‹à¤Ÿ  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>c;

if (c=='h'){

m=(n-(2000*k)-500*l)/200; 

cout<<"â‚¹200 à¤•à¥‡ "<< m <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·    â‚¹"<<(n-(2000*k)-500*l-200*m)<<"\n"<<"\n";

mm=n-(2000*k)-500*l-200*m;

if (mm==0)

goto final;

else if (mm<100)

goto fifty;

hundred:	

cout<<"â‚¹100 à¤•à¥‡ à¤¨à¥‹à¤Ÿ  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>d;

if (d=='h'){

o=(n-(2000*k)-500*l-200*m)/100; 

cout<<"â‚¹100 à¤•à¥‡ "<< o <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·    â‚¹"<<(n-(2000*k)-500*l-200*m-100*o)<<"\n"<<"\n";

oo=n-(2000*k)-500*l-200*m-100*o;

if (oo==0)

goto final;

else if (oo<50)

goto twenty;

fifty:

cout<<"â‚¹50 à¤•à¥‡ à¤¨à¥‹à¤Ÿ  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>e;

if (e=='h'){

p=(n-(2000*k)-500*l-200*m-100*o)/50; 

cout<<"â‚¹50 à¤•à¥‡ "<< p <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·   â‚¹"<<(n-(2000*k)-500*l-200*m-100*o-p*50)<<"\n"<<"\n";

pp=(n-(2000*k)-500*l-200*m-100*o-p*50);

if (pp==0)

goto final;

else if (pp<20)

goto ten;

twenty:

cout<<"â‚¹20 à¤•à¥‡ à¤¨à¥‹à¤Ÿ  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>f;

if (f=='h'){

q=(n-(2000*k)-500*l-200*m-100*o-p*50)/20; 

cout<<"â‚¹20 à¤•à¥‡ "<< q <<" à¤¨à¥‹à¤Ÿ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·   â‚¹"<<(n-(2000*k)-500*l-200*m-100*o-p*50-20*q)<<"\n"<<"\n";

qq=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q);

if (qq==0)

goto final;

else if (qq<10)

goto five;

ten:

cout<<"â‚¹10 à¤•à¥‡ à¤¨à¥‹à¤Ÿ/à¤¸à¤¿à¤•à¥à¤•à¥‡  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ -: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>g;

if (g=='h'){

r=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q)/10; 

cout<<"â‚¹10 à¤•à¥‡ "<<r <<" à¤¨à¥‹à¤Ÿ/à¤¸à¤¿à¤•à¥à¤•à¥‡ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·    â‚¹"<<(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r)<<"\n"<<"\n";

rr=n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r;

if (rr==0)

goto final;

else if (rr<5)

goto two;

five:

cout<<"â‚¹5 à¤•à¥‡ à¤¸à¤¿à¤•à¥à¤•à¥‡  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>i;

if (i=='h'){

s=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r)/5; 

cout<<"â‚¹5 à¤•à¥‡ "<< s <<"  à¤¸à¤¿à¤•à¥à¤•à¥‡ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤·   â‚¹"<<(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r-5*s)<<"\n"<<"\n";

ss=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r-5*s);

if (ss==0)

goto final;

else if (ss<2)

goto one;

two:

cout<<"â‚¹2 à¤•à¥‡ à¤¸à¤¿à¤•à¥à¤•à¥‡  à¤•à¥‹ à¤¶à¤¾à¤®à¤¿à¤² à¤•à¤°à¤¨à¤¾ à¤¹à¥ˆ-: à¤¹à¤¾à¤‚ à¤•à¥‡ à¤²à¤¿à¤  h à¤²à¤¿à¤–à¥‡ à¤…à¤¨à¥à¤¯à¤¥à¤¾ n " ;

cin>>j;

if (j=='h'){

t=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r-5*s)/2; 

cout<<"â‚¹2 à¤•à¥‡ "<<t <<" à¤¸à¤¿à¤•à¥à¤•à¥‡ "<<"\n"<<"\n";}

cout<<"à¤¶à¥‡à¤· â‚¹"<<(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r-5*s-2*t)<<"\n"<<"\n";

one:

u=(n-(2000*k)-500*l-200*m-100*o-p*50-20*q-10*r-5*s-2*t)/1; 

cout<<"â‚¹1 à¤•à¥‡ "<< u <<" à¤¸à¤¿à¤•à¥à¤•à¥‡ "<<"\n"<<"\n";

final :

cout<<"à¤¨à¥‹à¤Ÿà¥‹/à¤¸à¤¿à¤•à¥à¤•à¥‡ à¤•à¥€ à¤¸à¤‚à¤–à¥à¤¯à¤¾ à¤‡à¤¸ à¤ªà¥à¤°à¤•à¤¾à¤° à¤¹à¥ˆà¤‚"<<"\n";

cout<<"  à¤¨à¥‹à¤Ÿ   : " <<" à¤¸à¤‚à¤–à¥à¤¯à¤¾ " <<"\n";

cout<<" â‚¹2000: " << k<<"\n";

cout<<"â‚¹500: " <<l <<"\n";

cout<<"â‚¹200: " << m<<"\n";

cout<<"â‚¹100: " << o <<"\n";

cout<<"â‚¹50: " <<  p<<"\n";

cout<<"â‚¹20: " << q <<"\n";

cout<<"â‚¹10: " << r <<"\n";

cout<<"â‚¹5: " << s <<"\n";

cout<<"â‚¹2: " << t <<"\n";

cout<<"â‚¹1: " << u ;

cout<<"\n"<<"\n"<<"ðŸ‘Œ thanks à¤§à¤¨à¥à¤¯à¤µà¤¾à¤¦ ";

}
